//! EPUB archive path and href helpers.
//!
//! These work on ZIP member names, not filesystem paths. Keeping them isolated
//! makes the OPF/link-rewrite code easier to read and test.

use percent_encoding::percent_decode_str;

/// Return the archive directory containing the OPF package file.
pub(super) fn opf_base_dir(opf_path: &str) -> String {
    opf_path
        .rsplit_once('/')
        .map(|(base, _)| base.to_string())
        .unwrap_or_default()
}

/// Return the archive directory containing a spine or asset file.
pub(super) fn archive_base_dir(path: &str) -> String {
    path.rsplit_once('/')
        .map(|(base, _)| base.to_string())
        .unwrap_or_default()
}

/// Resolve an EPUB href against an archive directory without escaping root.
///
/// This intentionally works on ZIP member paths, not filesystem paths. It strips
/// any fragment first, percent-decodes path bytes, rejects absolute archive paths,
/// and fails if `..` would climb above the EPUB root.
pub(super) fn resolve_archive_path(base: &str, href: &str) -> Result<String, String> {
    let href = percent_decode(href.split('#').next().unwrap_or(href));
    if href.starts_with('/') {
        return Err("EPUB manifest uses absolute archive paths, which are unsupported".into());
    }

    let mut parts: Vec<&str> = if base.is_empty() {
        Vec::new()
    } else {
        base.split('/').collect()
    };
    for part in href.split('/') {
        match part {
            "" | "." => {}
            ".." => {
                if parts.pop().is_none() {
                    return Err("EPUB manifest path escapes archive root".into());
                }
            }
            other => parts.push(other),
        }
    }
    Ok(parts.join("/"))
}

/// Split an EPUB href into archive path and optional fragment components.
pub(super) fn split_href(href: &str) -> (&str, Option<&str>) {
    match href.split_once('#') {
        Some((path, fragment)) => (path, Some(fragment)),
        None => (href, None),
    }
}

/// Percent-decode href/id text using a forgiving UTF-8-lossy conversion.
///
/// EPUBs are often generated by older tools. Lossy decoding keeps import robust
/// while still producing deterministic internal anchors.
pub(super) fn percent_decode(value: &str) -> String {
    percent_decode_str(value).decode_utf8_lossy().into_owned()
}
